### ISSUE TITLE
Infrastruktur som kode for Amplify backend

### ISSUE THREAD

**Issue by janhenrik** [Knowit-Objectnet/Dataplattform-issues#572]
Vi ønsker å implementere de delene av kompetansekartlegging som ikke er støttet i Amplify (som f.eks. SAML/Auth) som kode. Vi har valgt å teste ut CDK v2.

Vi starter øverst med Auth.

![Kompetansekartleggings-gui arkitekturkartlegging](https://user-images.githubusercontent.com/58101/153549663-49d80212-0410-481f-881f-ebc807c0da37.jpg)

**Comment by janhenrik** [comment]
Ref også knowit/Dataplattform-issues#583 som håndterer frontend.

Denne oppgaven vil også nå inkludere å skrive oss ut av Amplify på backend med CDK (dvs. Appsync, DynamoDB, Analytics (ny, ref. knowit/kompetansekartlegging-app#56), Auth, Lambda).

**Comment by krisstam** [comment]
Per nå fungerer CDK backenden med eksisterende front end. Det som mangler er å se på externalAPI, samt teste at all funksjonalitet er som før.

CDK versjonen kan for nå bli funnet her: https://github.com/krisstam/cdk-test
Det er i et privat repo akkurat nå, men bli nok skilt ut til eget repo etterhvert.

**Comment by krisstam** [comment]
CDK-versjonen av Kompetansekartlegging er nå blitt produksjonssatt.
Vi har flyttet repoet over til https://github.com/knowit/kompetansekartlegging-app
